const contacts = 'Contactos registrados en el período seleccionado, según su fecha de registro (hora de Guayaquil).'
const adsDates = 'El gasto y los resultados de Meta corresponden al período seleccionado, según la zona horaria de la cuenta publicitaria.'
const appointments = 'Cuenta contactos registrados en el período que tienen citas, aunque la cita sea de otra fecha. Solicitadas: tienen una cita pendiente o solicitada; confirmadas: tienen fecha de confirmación; realizadas: figuran como atendidas y sin inasistencia. Un contacto puede aparecer en varias categorías. Permite ver su avance comercial; no es el total de citas del período.'

export const metricDescriptions: Record<string, string> = {
  'Contactos interesados': `${contacts} Cada contacto nuevo cuenta una vez. Muestra la llegada de posibles clientes, no clics, conversaciones ni ventas.`,
  'Contactos desde anuncios de WhatsApp': `${contacts} Cuenta los que tienen un origen publicitario de WhatsApp registrado en su primer contacto. Permite reconocer la captación asociada a anuncios; no cuenta clics ni todas las conversaciones.`,
  'Sin origen publicitario identificado': `${contacts} No tienen registrado un origen desde anuncios de WhatsApp. Ayuda a identificar información faltante; no demuestra que hayan llegado sin publicidad.`,
  'Nivel de interés': `${contacts} Distribuye su clasificación actual en bajo, medio, alto o sin clasificar. Orienta el seguimiento; no es una probabilidad de venta ni su clasificación histórica al cierre del período.`,
  'Citas programadas': 'Citas cuya fecha prevista está dentro del período seleccionado (hora de Guayaquil) y se clasifican como programadas. Ayuda a organizar la atención; no significa que ya se hayan realizado y puede incluir contactos registrados antes del período.',
  'Citas realizadas': 'Citas cuya fecha prevista está dentro del período seleccionado (hora de Guayaquil), atendidas y no futuras, canceladas ni marcadas como inasistencia. Mide atención realizada, no ventas; puede incluir contactos registrados antes del período.',
  'Canceladas / No asistieron': 'Citas con fecha prevista en el período seleccionado (hora de Guayaquil), separadas entre canceladas e inasistencias. Ayuda a revisar oportunidades de seguimiento; no son ventas perdidas confirmadas.',
  'Ventas del período': 'Cuenta cierres con fecha de venta dentro del período seleccionado (hora de Guayaquil), aunque el contacto se registrara antes. El importe suma valores conocidos; si faltan importes o hay monedas incompatibles puede no estar disponible. Muestra ventas registradas, no cobros recibidos.',
  'Contratos anulados': 'Contratos que actualmente figuran como anulados en el proyecto. No se filtran por fecha de anulación porque no está disponible. Permite conocer el estado actual; no indica cuántos se anularon en el período seleccionado.',
  'Costo promedio por contacto': `Divide el gasto del anuncio entre los contactos nuevos únicos registrados en el período (hora de Guayaquil), atribuidos al primer origen publicitario verificable guardado. Una interacción posterior con otro anuncio no cuenta como nueva adquisición. Los totales dividen la suma del gasto entre sus contactos únicos; no promedian promedios. ${adsDates} Si gastaste $20 y llegaron 10 contactos, el promedio es $2. No significa que cada persona haya costado exactamente eso. Con gasto conocido y cero contactos se indica Sin contactos nuevos; si falta el gasto, No disponible.`,
  'Gasto reportado por Meta': `${adsDates} Dinero que Meta informa como gastado, no el presupuesto asignado. Ayuda a comparar inversión y captación. Si figura pendiente de actualizar, se muestra el último dato guardado.`,
  'Gasto ejecutado': `${adsDates} Gasto de la campaña; si no está disponible, se usa la suma disponible de sus anuncios. Muestra inversión realizada, no presupuesto. Puede estar incompleto si faltan datos.`,
  'Suma de anuncios': `${adsDates} Suma el gasto disponible de los anuncios de la campaña. Sirve para compararlo con el total de campaña; puede faltar gasto si faltan anuncios o datos.`,
  'Comparación del gasto': `${adsDates} Compara el gasto de campaña con la suma de anuncios en la misma moneda. Una diferencia permite detectar cobertura incompleta; si falta la moneda o no coincide, no se comparan.`,
  'Resultado reportado por Meta': `${adsDates} Muestra un solo tipo de resultado elegido del informe de Meta, indicado junto al número. Puede contar conversaciones, contactos u otra acción; no equivale a contactos registrados en este sistema ni a ventas.`,
  'Citas': appointments,
  'Citas confirmadas / realizadas': appointments,
  'Ventas': 'Cierres con fecha de venta dentro del período seleccionado (hora de Guayaquil) asociados a contactos registrados en ese mismo período y al anuncio o unidad promocionada. Mide cierres registrados, no clics ni conversaciones; puede diferir del total de ventas del proyecto.',
  'Unidad': 'Inmueble al que corresponde esta fila. El período y los filtros delimitan los datos de cada indicador; permite comparar resultados por inmueble.',
  'Anuncio': `${contacts} Se agrupan por el anuncio identificado en el primer contacto. También pueden aparecer anuncios con datos de Meta sin contactos asociados. Permite comparar captación e inversión durante el período.`,
  'Anuncios': 'Cantidad de anuncios asociados de forma inequívoca a la unidad en este informe del período. Permite conocer qué publicidad se está agrupando; no cuenta contactos ni visitas.',
  'Propiedad anunciada': 'Propiedad identificada por una confirmación guardada o un enlace directo del anuncio a una unidad válida. Se usa la identificación actual incluso para períodos anteriores. No se deduce por nombres, imágenes ni intereses posteriores del contacto. No oculta anuncios ni cambia sus gastos o contactos. Las correcciones cambian la etiqueta también en informes anteriores, sin repartir el gasto.',
  'Visitas registradas': 'Cuenta registros de visita a la sala de ventas vinculados a esta unidad, con inicio dentro del período seleccionado (hora de Guayaquil). Mide visitas registradas, no personas únicas, clics ni recorridos virtuales. Una visita puede estar vinculada a varias unidades.',
  'Interés en la unidad': `${contacts} Cuenta los vinculados a la unidad que no la han descartado. Permite comparar el interés comercial; una persona puede interesarse por varias unidades.`,
  'Reservas': 'Titulares identificados de unidades actualmente reservadas en el proyecto, incluso si su contacto se registró antes del período. Es un estado actual, no reservas realizadas durante esas fechas. Sin titular único se indica que no está determinado; una reserva no es una venta.',
  'Importe': 'Suma los precios de cierre conocidos de las ventas de la unidad con fecha de venta dentro del período seleccionado (hora de Guayaquil). Mide el valor registrado de las ventas, no los pagos recibidos. Si no hay importes conocidos, se muestra No disponible.',
  'Unidad no determinada': `${contacts} Cuenta los que tienen citas sin unidad vinculada o estado de reserva sin unidad reservada identificada. Las citas pueden ser de cualquier fecha. Ayuda a completar información; no equivale al total de citas del período.`,
  'Titular no determinado': 'Unidades actualmente reservadas del proyecto sin un único titular comprobado, sin filtro por fecha de reserva. Ayuda a revisar información pendiente; no se asigna la reserva a una persona por suposición.',
  'Actividad del CRM (todos los orígenes)': `${contacts} Incluye anuncios externos y sin identificar; no es un total de publicidad de La Vilet. Las citas usan su fecha prevista y las ventas su fecha de cierre dentro del período. Las reservas y contratos anulados reflejan su estado actual. Las campañas y anuncios de toda la cuenta se muestran más abajo.`,
  'Por campaña': `${contacts} Agrupa contactos e inversión por campaña. ${adsDates} Permite comparar captación y costo entre campañas.`,
  'Por anuncio': `${contacts} Agrupa por el anuncio identificado en el primer contacto. ${adsDates} Las citas de esos contactos pueden ser de otras fechas. Permite evaluar la publicidad sin equiparar contactos con resultados de Meta.`,
  'Por unidad promocionada': `${contacts} Agrupa anuncios vinculados a una sola unidad. ${adsDates} Las citas corresponden a esos contactos sin restringir la fecha de cita; las ventas sí usan el período. Permite comparar la publicidad de cada inmueble.`,
  'Por unidad: interés, citas y ventas': 'Compara actividad por inmueble del proyecto. Visitas registradas y ventas usan sus fechas dentro del período; interés y citas se asocian a contactos registrados en el período, aunque las citas sean de otras fechas. Las reservas reflejan el estado actual, sin filtro temporal.',
}

export const unitDescriptions: Record<string, string> = {
  'Citas': `${contacts} Cuenta una vez por unidad a cada contacto con una cita vinculada a ella, de cualquier fecha o estado. Sirve para conocer el interés en visitar; no cuenta citas realizadas ni el total de citas del período.`,
  'Ventas': 'Cierres de la unidad con fecha de venta dentro del período seleccionado (hora de Guayaquil), incluso de contactos registrados antes. Mide ventas registradas del inmueble, no reservas ni cobros.',
  'Nivel de interés': `${contacts} Clasificación actual de los contactos vinculados a esta unidad sin haberla descartado: bajo, medio, alto o sin clasificar. Ayuda a priorizar seguimiento; no incluye automáticamente a todos los que tienen citas o reservas.`,
}
