import assert from 'node:assert/strict'
import test from 'node:test'
import { selectWeeklyContactsForObjective, type WeeklyObjectiveContact } from './weeklyObjectiveQualification'
const config={objectiveId:'financing',ownGroupId:'financing',eligibleEventTypes:['asked_financing'],weeklyTarget:50,windowStart:'2026-09-18T00:00:00Z',windowEnd:'2026-09-25T00:00:00Z'}
const rules=[{eventType:'asked_financing',points:30,active:true,repeatable:false}]
const contact=(id:string,group:string,temp:'frio'|'tibio'|'caliente'='tibio',evidence=true,labels=[group]):WeeklyObjectiveContact=>({contactId:id,primaryGroupId:group,labels,temperature:temp,qualifiedAt:'2026-09-20T00:00:00Z',evidence:evidence?[{evidenceId:`e-${id}`,eventType:'asked_financing',occurredAt:'2026-09-22T00:00:00Z'}]:[]})
test('35 propios más 15 incorporados alcanzan 50',()=>{const rows=[...Array.from({length:35},(_,i)=>contact(`o${i}`,'financing')),...Array.from({length:15},(_,i)=>contact(`x${i}`,'visit','caliente',true,['visit','financing']))];const r=selectWeeklyContactsForObjective(rows,rules,config);assert.deepEqual({own:r.own,incorporated:r.incorporated,total:r.total,missing:r.missingToTarget},{own:35,incorporated:15,total:50,missing:0})})
test('admite más de 50 elegibles sin recortar',()=>{const r=selectWeeklyContactsForObjective(Array.from({length:63},(_,i)=>contact(`c${i}`,i<40?'financing':'other')),rules,config);assert.equal(r.total,63);assert.equal(r.missingToTarget,0)})
test('dos elegibles dejan faltante 48',()=>{const r=selectWeeklyContactsForObjective([contact('a','financing'),contact('b','other')],rules,config);assert.equal(r.total,2);assert.equal(r.missingToTarget,48)})
test('excluye fríos, ausencia de evidencia y evidencia fuera de ventana',()=>{const old=contact('old','other');old.evidence[0].occurredAt='2026-09-01T00:00:00Z';const r=selectWeeklyContactsForObjective([contact('cold','financing','frio'),contact('none','other','caliente',false),old],rules,config);assert.equal(r.total,0);assert.equal(r.missingToTarget,50)})
test('múltiples grupos y reintentos son deterministas y no duplican',()=>{const multi=contact('same','other','tibio',true,['other','financing','visit']);const first=selectWeeklyContactsForObjective([multi,{...multi}],rules,config);const retry=selectWeeklyContactsForObjective([{...multi},multi],rules,config);assert.deepEqual(first,retry);assert.deepEqual(first.incorporatedContactIds,['same'])})
test('falta relación de reglas detiene solo ese objetivo',()=>{const r=selectWeeklyContactsForObjective([],rules,{...config,eligibleEventTypes:['not_mapped']});assert.equal(r.status,'configuration_pending');assert.deepEqual(r.configurationPending,['scoring_rule:not_mapped'])})
test('selección no crea eventos de conversión',()=>{const r=selectWeeklyContactsForObjective([contact('a','financing')],rules,config);assert.equal('event_name' in r,false);for(const name of ['Purchase','Schedule','QualifiedLead'])assert.equal(JSON.stringify(r).includes(name),false)})
