import { PURCHASE_EVIDENCE_RULES } from './purchase-evidence'

/** Domain-specific details live in the adjoining extraction sections. Keep
 * this shared contract concise instead of repeating their full procedures. */
export const EXTRACTION_REQUEST_RULES = `
${PURCHASE_EVIDENCE_RULES}
Devuelva todos los campos del esquema. requests contiene TODAS las solicitudes independientes del mensaje actual, con evidencia literal (conserve sus errores). La única fuente adicional es consultas_pendientes, citando allí su evidencia original. El historial resuelve referencias y correcciones, no crea nuevas declaraciones, solicitudes ni consentimientos.
Asigne domain: property (proyecto, catálogo, precios, reserva informativa), financing (información o revisión financiera), visit (visita inmobiliaria), advisor (atención humana explícita o iniciar reserva), tracking (alta/baja de mensajes), courtesy (cortesía sin consulta nueva), other (ajeno o no resoluble). Separe cada duda adicional aunque una aceptación sea principal. La clasificación de alcance es provisional: interprete independientemente todo el mensaje. Datos, presupuesto y visitas de otro negocio no autorizan acciones inmobiliarias. opt_out sí es global.
Consultar el significado, utilidad o funcionamiento de un concepto, material o servicio inmobiliario presentado pertenece a property y project_information; no es other solo porque no pide una unidad. Resuelva el referente con la conversación y mantenga coherentes primary_intent y el dominio de cada solicitud apoyados en su evidencia actual. Informarse sobre un servicio no solicita iniciarlo ni autoriza gestiones.
Una corrección de categoría conserva el propósito de la consulta corregida: precio sigue siendo precio; cómo verlo sigue siendo visualización. resumen._turn_intent ayuda a resolverlo, pero no prevalece ante un cambio de tema explícito. Nombre/residencia no eligen una categoría. Repetir el sustantivo del cliente no demuestra que existan varios edificios.
Responda a la última pregunta REAL entregada y su objeto, incluidos target_ids/candidate_ids. Aceptar ayuda para financiamiento puede coexistir con preguntar cómo proceder: financing_consent=true, requested_advisor=false salvo petición humana explícita. Una interrogación no anula la aceptación. Aceptar una oferta de dos acciones distintas sin escoger deja answer_to_previous.kind=uncertain; no elige unidad, autoriza trámite ni reserva. Una oferta de un solo objeto sí puede aceptarse. La aceptación guardada en resumen._financing_journey es continuidad, no una novedad que deba extraerse otra vez.
requested_advisor, opt_out y consent_granted requieren su fragmento literal actual en action_evidence; si no existe, null. Consultar precio, pedir brochure, agradecer o aceptar detalles no pide asesor ni autoriza seguimiento. Pedir ayuda para coordinar horario corresponde a requested_visit/visit_needs_help, no por sí solo a asesor. Resuelva fechas parciales en la coordinación durable. Extraiga la entidad financiera elegida aunque no figure en las disponibles; elegirla no es una mera consulta ni implica otros consentimientos.
Iniciar reserva/separación: domain=advisor y turn_semantics.reservation.kind=request. Preguntar requisitos/monto/proceso: domain=property y kind=information. asked_reservation puede acompañar ambos y nunca sustituye esa distinción. Conserve consultas simultáneas y no extienda una negativa parcial a una petición posterior.
full_name puede ser el nombre de trato para la presentación, sin exigir apellidos ni copiar WhatsApp. Cite su declaración o respuesta a la pregunta de nombre en profile_evidence. No lo confunda con el nombre legal completo requerido después. residence_city/country solo expresan residencia ACTUAL inequívoca o respuesta a esa pregunta pendiente: nunca origen, nacionalidad, estancia temporal, destino de compra, teléfono ni inferencias geográficas. Cite la declaración actual completa; no rellene país desde ciudad ni ciudad desde país. Sin declaración o ante negativa, null. Nombre y residencia son perfil, no interés inmobiliario ni visita.
Una pregunta nueva que empieza por «no» no niega automáticamente el presupuesto pendiente. «Vivienda» indica grupo residencial, sin elegir tipología ni presupuesto. Consultar opciones, planta o máximo no selecciona ni reserva. Diferencie código literal de referencia implícita resuelta con el historial. Un importe aproximado con finalidad clara se conserva como estimación; la incertidumbre sobre una decisión no pide atención humana. No transforme un presupuesto en entrada ni una información comercial en consentimiento. Un archivo sin interpretar no da evidencia: interprete solo su texto legible acompañante, sin recuperar intenciones antiguas para llenar el vacío.`
