'use client'
/* eslint-disable @next/next/no-img-element -- QR is generated locally as a data URL. */
import { useEffect, useRef, useState } from 'react'
import { useTourLanguage } from '@/lib/tour/tourLocale'
import { Menu, X, Maximize, Minimize, ArrowLeft, Home, Building2, Search, Store, Scan, Trees, HardHat, MapPin, ChevronRight } from 'lucide-react'
import { FocusScope } from 'react-aria'
import QRCode from 'qrcode'
import type { TourPublicCatalog, TourUnitSummary } from '@/types/tour'
import { UNIT_MODEL_ORIGIN, unitModelUrl } from '@/lib/tour/unitModels'
import { COOKIE_BANNER_ENABLED, openCookiePreferences } from '@/lib/tour/consent'
import { SITE } from '@/lib/marketing/site'
import { constructionProgress } from '@/lib/tour/constructionProgress'
import { emptyUnitFilters, filterShowroomUnits, publicShowroomUrl } from '@/lib/tour/showroomMenu'
type Section='home'|'areas'|'units'|'shops'|'tour'|'amenities'|'progress'|'contact'
const names={es:['Inicio / edificio','Áreas del proyecto','Buscar departamentos','Locales comerciales','Departamento modelo / 360°','Amenidades','Avance de obra','Ubicación y contacto'],en:['Home / building','Project areas','Find an apartment','Commercial units','Model apartment / 360°','Amenities','Construction progress','Location and contact']}
const icons=[Home,Building2,Search,Store,Scan,Trees,HardHat,MapPin]
const sections:Section[]=['home','areas','units','shops','tour','amenities','progress','contact']
export function ShowroomMenu({units,catalog,selected,onHome,onPick,onTour,onClosePanels,root}:{units:TourUnitSummary[];catalog:TourPublicCatalog|null;selected:TourUnitSummary|null;onHome:()=>void;onPick:(u:TourUnitSummary)=>void;onTour:(u:TourUnitSummary)=>void;onClosePanels:()=>void;root:React.RefObject<HTMLDivElement|null>}){
 const [content,setContent]=useState(false)
 const [open,setOpen]=useState(false),[section,setSection]=useState<Section>('home')
 const {locale:lang,setLocale:setLang,t:translate}=useTourLanguage()
 const [filters,setFilters]=useState(emptyUnitFilters),[full,setFull]=useState(false),[notice,setNotice]=useState(''),[share,commitShare]=useState<TourUnitSummary|null>(null),[qr,setQr]=useState('')
 const shareUrl=share?publicShowroomUrl(share.unit_number,UNIT_MODEL_ORIGIN)+(lang==='en'?'&lang=en':''):''
 const setShare=(unit:TourUnitSummary|null)=>{setQr('');commitShare(unit)}
 const [amenities,setAmenities]=useState<Array<{amenity_name:string;description:string|null}>>([]),[amenitiesState,setAmenitiesState]=useState('idle')
 const button=useRef<HTMLButtonElement>(null)
 const t=(es:string,en:string)=>lang==='es'?es:en
 useEffect(()=>{const sync=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync)},[])
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);button.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open])
 useEffect(()=>{if(!share)return;let active=true;const url=publicShowroomUrl(share.unit_number,UNIT_MODEL_ORIGIN)+(lang==='en'?'&lang=en':'');void QRCode.toDataURL(url,{width:224,margin:4,errorCorrectionLevel:'M'}).then(value=>{if(active)setQr(value)}).catch(()=>{if(active)setNotice('No se pudo generar el QR; use el enlace.')});return()=>{active=false}},[share,lang])
 useEffect(()=>{if(section!=='amenities' || !open)return;const controller=new AbortController();void fetch('/api/tour/amenities',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{setAmenities(data.items);setAmenitiesState('ready')}).catch(()=>{if(!controller.signal.aborted)setAmenitiesState('error')});return()=>controller.abort()},[section,open])
 const choices=(key:'floor'|'category'|'status'|'bedrooms')=>[...new Set(units.map(u=>u[key]).filter(v=>v!=null && v!==''))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}))
 const filtered=filterShowroomUnits(units,filters,section==='shops')
 const close=()=>{setOpen(false);button.current?.focus()}
 const go=(next:Section)=>{setContent(true);setSection(next);if(next==='amenities')setAmenitiesState('loading');if(next==='units'||next==='shops'||next==='tour')setFilters(emptyUnitFilters);setShare(null);setNotice('');if(next==='home'){onHome();close()}else onClosePanels()}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.current?.requestFullscreen)await root.current.requestFullscreen();else setNotice(t('Este navegador no permite pantalla completa.','Fullscreen is unavailable in this browser.'))}catch{setNotice(t('No se pudo cambiar a pantalla completa.','Fullscreen could not be changed.'))}}
 const fields=[['floor',t('Piso','Floor')],['bedrooms',t('Dormitorios','Bedrooms')],['category',t('Tipo','Type')],['status',t('Disponibilidad','Availability')]] as const
 return <>
  <header aria-label="Controles del showroom" className="absolute inset-x-0 top-0 z-[90] flex h-[calc(4rem+env(safe-area-inset-top))] items-center gap-2 border-b border-[#bda27e]/25 bg-[#14110e]/95 px-3 pt-[env(safe-area-inset-top)] text-[#f7f3ee] backdrop-blur-md sm:px-5">
   <button ref={button} type="button" aria-label={t('Abrir menú del showroom','Open showroom menu')} aria-expanded={open} onClick={()=>{onClosePanels();setContent(false);setShare(null);setNotice('');setOpen(true)}} className="rounded-full border border-[#bda27e]/50 bg-[#29251e]/90 p-3 text-[#f7f3ee]"><Menu size={20}/></button>
   <button type="button" aria-label={full?t('Salir de pantalla completa','Exit fullscreen'):t('Pantalla completa','Fullscreen')} onClick={()=>void fullscreen()} className="rounded-full border border-[#bda27e]/50 bg-[#29251e]/90 p-3 text-[#f7f3ee]">{full?<Minimize size={20}/>:<Maximize size={20}/>}</button>
   <span className="ml-2 min-w-0 truncate font-serif text-sm tracking-[.22em] sm:text-lg">LA VILET</span>
   <span className="ml-auto hidden text-[10px] uppercase tracking-[.2em] text-[#bda27e] lg:block">Showroom 360°</span>
   <a href="/inicio" aria-label={t('Volver a la página web','Back to website')} title={t('Volver a la página web','Back to website')} className="ml-auto inline-flex min-h-11 shrink-0 items-center gap-1.5 rounded-full border border-[#bda27e]/50 px-3 text-xs text-[#f7f3ee] transition-colors hover:bg-[#bda27e]/20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#bda27e] lg:ml-3">
    <ArrowLeft size={16} aria-hidden="true"/><span className="sm:hidden">{t('Volver','Back')}</span><span className="hidden sm:inline">{t('Volver a la web','Back to website')}</span>
   </a>
  </header>
  {!open && notice?<p role="status" className="absolute left-3 top-20 z-[90] rounded bg-[#f7f3ee] p-2 text-xs text-[#29251e]">{notice}</p>:null}
  {open?<div className="absolute inset-0 z-[200] flex bg-black/30 p-2 sm:p-3" onClick={close}>
   <FocusScope contain restoreFocus autoFocus><aside role="dialog" aria-modal="true" aria-label={t('Menú La Vilet','La Vilet menu')} lang={lang} onClick={e=>e.stopPropagation()} className={`flex h-full w-full flex-col overflow-y-auto rounded-2xl bg-[#f7f3ee] p-5 text-[#29251e] shadow-2xl ${content?'max-w-md':'max-w-[320px]'}`}>
    <header className="flex items-center justify-between border-b border-[#bda27e]/40 pb-4"><div><p className="font-serif text-3xl tracking-[.16em]">LA VILET</p><p className="mt-2 text-xs">{SITE.city}</p></div><button type="button" aria-label={t('Cerrar menú','Close menu')} onClick={close} className="rounded-full border border-[#bda27e]/50 p-2"><X/></button></header>
    {!content?<nav aria-label={t('Secciones','Sections')} className="my-6 flex flex-col gap-1">{sections.map((key,i)=>{const Icon=icons[i];return <button type="button" key={key} aria-current={section===key?'page':undefined} onClick={()=>go(key)} className={`flex min-h-11 items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13px] transition-colors focus-visible:outline-2 focus-visible:outline-[#8e7654] ${section===key?'bg-[#ded3c1]':'hover:bg-[#eae3d8]'}`}><Icon size={18} strokeWidth={1.5} className="shrink-0 text-[#8e7654]"/><span className="flex-1">{names[lang][i]}</span><ChevronRight size={14} className="shrink-0 text-[#8e7654]"/></button>})}</nav>:<button type="button" onClick={()=>{setContent(false);setShare(null);setNotice('')}} className="my-4 flex min-h-11 items-center gap-2 self-start text-sm text-[#756044]"><ArrowLeft size={18}/>{t('Volver al menú','Back to menu')}</button>}
    <label className={`flex items-center gap-3 text-sm ${content?'mb-4':'mt-auto border-t border-[#bda27e]/30 pt-4'}`}>{t('Idioma','Language')}<select aria-label="Idioma / Language" value={lang} onChange={e=>setLang(e.target.value as 'es'|'en')} className="rounded border border-[#bda27e] bg-transparent p-2"><option value="es">Español</option><option value="en">English</option></select></label>
    {lang==='en'?<p className="mb-3 text-xs">Original plans, images, videos and published descriptions without an English version remain in their original language.</p>:null}
    {content?<div>
    {(section==='units'||section==='shops'||section==='tour')?<section>
     <h2 className="mb-3 font-serif text-2xl">{names[lang][sections.indexOf(section)]}</h2>
     {section!=='tour'?<div className="mb-4 grid grid-cols-2 gap-2">
      <label className="col-span-2 text-xs">{t('Número de unidad','Unit number')}<input value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})} className="mt-1 w-full rounded border border-[#bda27e]/50 bg-white p-2"/></label>
      {fields.filter(([key])=>section!=='shops'||(key!=='bedrooms'&&key!=='category')).map(([key,label])=><label key={key} className="text-xs">{label}<select aria-label={label} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})} className="mt-1 w-full rounded border border-[#bda27e]/50 bg-white p-2"><option value="">{t('Todos','All')}</option>{choices(key).map(value=><option key={String(value)} value={String(value)}>{translate(String(value))}</option>)}</select></label>)}
      {(['min','max'] as const).map(key=><label key={key} className="text-xs">{key==='min'?t('Superficie mínima (m²)','Minimum area (m²)'):t('Superficie máxima (m²)','Maximum area (m²)')}<input type="number" min="0" value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})} className="mt-1 w-full rounded border border-[#bda27e]/50 bg-white p-2"/></label>)}
      <button type="button" onClick={()=>setFilters(emptyUnitFilters)} className="text-left text-xs underline">{t('Limpiar filtros','Clear filters')}</button>
     </div>:<p className="mb-3 text-sm">{t('Elija una unidad. Los recursos de tipología se muestran como referencia, no como una vista exterior exclusiva.','Choose a unit. Typology resources are references, not a verified exterior view from that unit.')}</p>}
     <p className="mb-2 text-xs">{filtered.length} {t('unidades','units')}</p>
     <ul className="divide-y divide-[#bda27e]/30">{filtered.map(u=><li key={u.id} className="py-3"><p className="font-medium">{u.category==='local'?t('Local','Commercial unit'):t('Unidad','Unit')} {u.unit_number}</p><p className="my-1 text-xs">{u.floor || '—'} · {u.area_total_m2!=null?`${u.area_total_m2} m²`:'—'}{u.category!=='local'?` · ${u.bedrooms ?? '—'} ${t('dormitorios','bedrooms')}`:''} · {translate(u.status)}</p><div className="flex flex-wrap gap-4 text-sm"><button type="button" className="underline" onClick={()=>{onPick(u);close()}}>{t('Abrir ficha','Open details')}</button><button type="button" className="underline" onClick={()=>{const typ=catalog?.typologies.find(v=>(u.unit_type_id&&v.id===u.unit_type_id)||(u.typology_code&&v.code===u.typology_code));if(typ?.panorama||typ?.rooms.some(r=>r.url||r.scenes.length)){onTour(u);close()}else setNotice(t(`La unidad ${u.unit_number} todavía no tiene recorrido 360° disponible.`,`Unit ${u.unit_number} has no available 360° tour.`))}}>360°</button><button type="button" className="underline" onClick={()=>setShare(u)}>QR</button>{unitModelUrl({...u})?<a href={unitModelUrl({...u})!} target="_blank" rel="noopener noreferrer" className="underline">{t('Modelo 3D','3D model')}</a>:null}</div></li>)}</ul>
     {!filtered.length?<p className="py-4 text-sm">{t('No hay unidades que coincidan con estos filtros.','No units match these filters.')}</p>:null}
    </section>:null}
    {section==='home'?<button type="button" className="rounded border border-[#bda27e] p-3" onClick={()=>{onHome();close()}}>{t('Ver edificio y pisos','View building and floors')}</button>:null}
    {section==='areas'?<section><h2 className="font-serif text-2xl">{t('Distribución del proyecto','Project layout')}</h2><p className="my-3 text-sm">{t('Explore los pisos y la ubicación de viviendas y locales en el plano del edificio. Las instalaciones compartidas están en Amenidades.','Explore floors and the location of homes and commercial units. Shared facilities are listed under Amenities.')}</p><button type="button" className="underline" onClick={()=>{onHome();close()}}>{t('Abrir plano del edificio','Open building plan')}</button></section>:null}
    {section==='amenities'?<section><h2 className="font-serif text-2xl">{t('Instalaciones compartidas','Shared facilities')}</h2>{amenities.map((a,i)=><article key={i} className="border-b border-[#bda27e]/30 py-3"><h3>{translate(a.amenity_name)}</h3>{a.description?<p className="text-sm">{translate(a.description)}</p>:null}</article>)}{!amenities.length?<p className="mt-3 text-sm">{amenitiesState==='loading'?t('Consultando…','Loading…'):amenitiesState==='error'?t('No se pudieron consultar las instalaciones.','Facilities could not be loaded.'):t('Aún no hay instalaciones publicadas.','No facilities have been published yet.')}</p>:null}</section>:null}
    {section==='progress'?<section><h2 className="font-serif text-2xl">{t('Avance de obra','Construction progress')}</h2>{constructionProgress.length?constructionProgress.map(update=><article key={update.id} className="my-4"><time dateTime={update.date}>{update.date}</time><h3 className="font-medium">{translate(update.title)}</h3><p className="text-sm">{translate(update.description)}</p>{update.media.map(media=><figure key={media.url} className="my-3">{media.type==='image'?<img src={media.url} alt={media.caption} className="w-full rounded"/>:<video src={media.url} controls preload="metadata" className="w-full rounded"/>}<figcaption className="text-xs">{translate(media.caption)}</figcaption></figure>)}</article>):<p className="mt-3 text-sm">{t('Todavía no hay un registro de obra publicado con fotos, fecha y descripción. Puede solicitar la información al equipo.','A dated construction photo log has not been published yet. Contact our team for information.')}</p>}<a className="mt-3 inline-block underline" href={`mailto:${SITE.email}`}>{SITE.email}</a></section>:null}
    {section==='contact'?<section><h2 className="font-serif text-2xl">{t('Ubicación y contacto','Location and contact')}</h2><p className="my-3">{SITE.location.address}</p><div className="flex flex-col gap-3"><a href={SITE.location.mapsUrl} target="_blank" rel="noopener noreferrer" className="underline">{t('Abrir ubicación en el mapa','Open location on map')}</a><a href={`mailto:${SITE.email}`} className="underline">{SITE.email}</a>{SITE.whatsapp?<a href={`https://wa.me/${SITE.whatsapp}`} target="_blank" rel="noopener noreferrer" className="underline">WhatsApp</a>:null}</div></section>:null}
    {selected&&!share?<button type="button" onClick={()=>setShare(selected)} className="mt-6 self-start underline">{t('Compartir unidad','Share unit')} {selected.unit_number} · QR</button>:null}
    {share?<section className="mt-5 border-t border-[#bda27e]/40 pt-4"><h3>{t('Compartir unidad','Share unit')} {share.unit_number}</h3>{qr?<img src={qr} width={224} height={224} alt={`QR ${share.unit_number}`} className="my-2 max-w-full"/>:null}<a href={shareUrl} target="_blank" rel="noopener noreferrer" className="break-all text-xs underline">{shareUrl}</a><p className="mt-2 text-xs">{t('El QR abre el recorrido público de esta unidad.','The QR opens the public tour for this unit.')}</p></section>:null}
    </div>:null}
    <footer className="mt-6 flex flex-wrap gap-4 border-t border-[#bda27e]/30 pt-4 text-xs"><a href="/inicio" className="underline">{t('Volver a la web','Back to website')}</a>{COOKIE_BANNER_ENABLED?<button type="button" className="underline" onClick={()=>{close();openCookiePreferences()}}>{t('Preferencias de cookies','Cookie preferences')}</button>:null}</footer>
    {notice?<p role="status" className="mt-3 text-sm">{notice}</p>:null}
   </aside></FocusScope>
  </div>:null}
 </>
}
