/* eslint-disable @typescript-eslint/no-require-imports -- Node CommonJS browser harness. */
﻿const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),{webpack}=require('next/dist/compiled/webpack/webpack'),{compile}=require('@tailwindcss/node');
const root=process.cwd(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'ficha-layout-'));
(async()=>{
 const entry=path.join(dir,'entry.tsx'),loader=path.join(dir,'loader.cjs'),empty=path.join(dir,'empty.cjs');
 fs.writeFileSync(loader,`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=s=>ts.transpileModule(s,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText`);fs.writeFileSync(empty,'module.exports=()=>""');
 fs.writeFileSync(entry,`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {TourFichaDrawer} from '${path.join(root,'src/components/tour/TourFichaDrawer').replace(/\\/g,'/')}';const units=[{id:'test',unit_number:'001',status:'disponible',floor:'Planta Baja',category:'departamento',published_commercial_price:210000,area_total_m2:87.97,bedrooms:1,bathrooms:1}];function App(){const [expanded,setExpanded]=useState(false);const [open,setOpen]=useState(true);return <div className='tour-root' style={{position:'fixed',inset:0,background:'#29251e'}}><header data-showroom-toolbar style={{position:'absolute',top:0,width:'100%',height:56,zIndex:120,color:'white'}}>LA VILET</header><TourFichaDrawer open={open} expanded={expanded} contained={location.search.includes('embedded')} typologyCode="A" units={units} onClose={()=>setOpen(false)} onVerFicha={()=>setExpanded(true)} onTour360={()=>{}} onRequestInfo={()=>{}} /></div>}createRoot(document.getElementById('root')).render(<App/>);`);
 await new Promise((resolve,reject)=>webpack({mode:'development',devtool:false,entry,output:{path:dir,filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],modules:[path.join(root,'node_modules')],alias:{'@':path.join(root,'src')}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:loader},{test:/\.css$/,use:empty}]}},(e,s)=>e?reject(e):s.hasErrors()?reject(Error(s.toString({all:false,errors:true}))):resolve()));
 const files=['src/components/tour/TourFichaDrawer.tsx','src/components/tour/UnitPublicQr.tsx','src/components/tour/QrShareButton.tsx'];const css=(await compile('@import "tailwindcss";',{base:root,onDependency(){}})).build(files.flatMap(f=>fs.readFileSync(f,'utf8').split(/[\s"'`]+/)))+fs.readFileSync('src/components/tour/tour-viewer.css','utf8');
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');res.end(req.url.endsWith('.js')?fs.readFileSync(path.join(dir,req.url.slice(1))):`<meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><div id="root"></div><script src="/bundle.js"></script>`)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();
 try{for(const [width,height] of [[390,640],[667,320],[740,360],[812,375],[844,390],[932,430],[900,500],[800,700],[1440,900]])for(const embedded of [false,true]){const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce',hasTouch:width<1000,isMobile:height<=500 || width<500});await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());await page.goto('http://127.0.0.1:'+server.address().port+(embedded?'/?embedded':''));const dialog=page.locator('.tour-ficha-sheet');await dialog.waitFor();
 const check=async()=>{const b=await dialog.boundingBox();const toolbar=await page.locator('[data-showroom-toolbar]').boundingBox();assert.ok(b.y>=toolbar.y+toolbar.height, 'ficha debajo de la barra');assert.ok(b.y+b.height<=height);assert.ok(b.x+b.width<=width);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)};
 await check();await page.getByRole('button',{name:'Ver Ficha',exact:true}).click();await page.getByRole('button',{name:'Descargar PDF',exact:true}).waitFor();await check();await page.getByRole('button',{name:'QR',exact:true}).click();const qr=page.getByRole('dialog',{name:'QR 001',exact:true});await qr.waitFor();await qr.getByRole('button',{name:'Cerrar',exact:true}).click();await qr.waitFor({state:'hidden'});await check();const footer=await page.getByRole('button',{name:'Descargar PDF',exact:true}).boundingBox();assert.ok(footer.y>=56 && footer.y+footer.height<=height);assert.ok(await page.locator('.tour-ficha-scroll').evaluate(el=>el.clientHeight>40));if(height<=500) await page.locator('[data-showroom-toolbar]').evaluate(el=>{el.style.height='120px';el.style.background='#222'});const close=dialog.locator(height<=500 || width<=700 ? '.tour-ficha-close' : '.tour-ficha-media-close');assert.ok(await close.evaluate(el=>{const r=el.getBoundingClientRect();return [[.2,.2],[.8,.2],[.5,.5],[.2,.8],[.8,.8]].every(([x,y])=>el.contains(document.elementFromPoint(r.x+r.width*x,r.y+r.height*y)))}),'X visible y sin superposicion');await close.click();await dialog.waitFor({state:'hidden'});await page.close();console.log('PASS simulated ficha',width,height,embedded)} }finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
