-- Prepared locally. Apply before transport-v2 runtime; no replay of queued sends.
BEGIN;
ALTER TABLE public.lv_integration_events ADD COLUMN IF NOT EXISTS ingest_order bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE OR REPLACE FUNCTION public.lv_app_stamp_ingestion()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
 IF NEW.kind IN ('inbound','advisor_outbound') THEN
  NEW.payload:=coalesce(NEW.payload,'{}'::jsonb)||jsonb_build_object('transportSequence',NEW.ingest_order);
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS lv_app_stamp_ingestion ON public.lv_integration_events;
CREATE TRIGGER lv_app_stamp_ingestion BEFORE INSERT ON public.lv_integration_events
 FOR EACH ROW EXECUTE FUNCTION public.lv_app_stamp_ingestion();

CREATE OR REPLACE FUNCTION public.lv_app_transport_contract()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT jsonb_build_object('version','transport-v2','max_events',200,'kommo_spacing_ms',400);
$$;

-- A response field belongs to a lead; a chat belongs to a contact. Both are
-- shared resources even when their canonical contact keys differ.
CREATE OR REPLACE FUNCTION public.lv_app_resources_overlap(p_left text,p_right text)
RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path='' AS $$
 SELECT coalesce(p_left=p_right OR (
  p_left~'^([1-9][0-9]*|contact):[1-9][0-9]*$' AND p_right~'^([1-9][0-9]*|contact):[1-9][0-9]*$'
  AND (split_part(p_left,':',2)=split_part(p_right,':',2)
   OR (split_part(p_left,':',1)~'^[1-9][0-9]*$' AND split_part(p_left,':',1)=split_part(p_right,':',1)))
 ),false);
$$;

CREATE OR REPLACE FUNCTION public.lv_app_receive(p_events jsonb)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE event jsonb; count_inserted integer:=0; added integer;
BEGIN
 IF p_events IS NULL OR jsonb_typeof(p_events)<>'array' OR jsonb_array_length(p_events)>200 THEN RAISE EXCEPTION 'INVALID_EVENTS'; END IF;
 FOR event IN SELECT value FROM jsonb_array_elements(p_events) LOOP
  IF coalesce(event->>'externalId','')='' OR coalesce(event->>'contactId','')='' THEN RAISE EXCEPTION 'INVALID_EVENT'; END IF;
  INSERT INTO lv_integration_events(tenant_id,project_id,event_key,kind,contact_key,payload,available_at)
  VALUES('a1b2c3d4-0001-4000-8000-000000000001','b1b2c3d4-0001-4000-8000-000000000001',
   'inbound:'||(event->>'externalId'),'inbound',(event->>'kommoId')||':'||(event->>'contactId'),event,now()+interval '30 seconds')
  ON CONFLICT(project_id,event_key) DO NOTHING;
  GET DIAGNOSTICS added=ROW_COUNT; count_inserted:=count_inserted+added;
 END LOOP;
 RETURN count_inserted;
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_receive_advisor_outbound(p_events jsonb)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE event jsonb; count_inserted integer:=0; added integer; resolved_kommo_id bigint; matched_ids bigint[];
BEGIN
 IF p_events IS NULL OR jsonb_typeof(p_events)<>'array' OR jsonb_array_length(p_events)>200 THEN RAISE EXCEPTION 'INVALID_EVENTS'; END IF;
 FOR event IN SELECT value FROM jsonb_array_elements(p_events) LOOP
  IF coalesce(event->>'externalId','')='' OR coalesce(event->>'contactId','')='' OR coalesce(event->>'userId','')='' THEN RAISE EXCEPTION 'INVALID_ADVISOR_EVENT'; END IF;
  resolved_kommo_id:=nullif(event->>'kommoId','')::bigint;
  IF coalesce(resolved_kommo_id,0)<=0 THEN
   SELECT array_agg(DISTINCT l.kommo_id) INTO matched_ids FROM leads l
    WHERE l.tenant_id='a1b2c3d4-0001-4000-8000-000000000001' AND l.project_id='b1b2c3d4-0001-4000-8000-000000000001'
     AND l.contact_id::text=event->>'contactId' AND l.kommo_id>0;
   resolved_kommo_id:=CASE WHEN cardinality(matched_ids)=1 THEN matched_ids[1] END;
   IF cardinality(matched_ids)>1 THEN event:=event||jsonb_build_object('identityAmbiguous',true); END IF;
  END IF;
  IF coalesce(resolved_kommo_id,0)>0 THEN event:=jsonb_set(event,'{kommoId}',to_jsonb(resolved_kommo_id),true); END IF;
  INSERT INTO lv_integration_events(tenant_id,project_id,event_key,kind,contact_key,payload,available_at)
  VALUES('a1b2c3d4-0001-4000-8000-000000000001','b1b2c3d4-0001-4000-8000-000000000001',
   'advisor_outbound:'||(event->>'externalId'),'advisor_outbound',
   coalesce(nullif(resolved_kommo_id,0)::text,'contact')||':'||(event->>'contactId'),event,now()+interval '30 seconds')
  ON CONFLICT(project_id,event_key) DO NOTHING;
  GET DIAGNOSTICS added=ROW_COUNT; count_inserted:=count_inserted+added;
 END LOOP;
 RETURN count_inserted;
END $$;

-- Maintenance does not send Kommo messages and owns a separate lease. The old
-- global send worker still excludes contact workers until Salesbot field-read
-- timing has been verified; this migration does not guess when delivery occurs.
CREATE OR REPLACE FUNCTION public.lv_app_worker_lock(p_token uuid,p_action text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id uuid;
BEGIN
 IF p_token IS NULL THEN RAISE EXCEPTION 'TOKEN_REQUIRED'; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('lavilet-conversation-workers'));
 IF p_action='acquire' THEN
  IF EXISTS(SELECT 1 FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001'
    AND kind='lock' AND starts_with(event_key,'__conversation__:') AND lease_until>now()) THEN RETURN false; END IF;
  INSERT INTO lv_integration_events(tenant_id,project_id,event_key,kind,status,claim_token,lease_until)
   VALUES('a1b2c3d4-0001-4000-8000-000000000001','b1b2c3d4-0001-4000-8000-000000000001','__worker__','lock','completed',p_token,now()+interval '3 minutes')
   ON CONFLICT(project_id,event_key) DO UPDATE SET claim_token=p_token,lease_until=now()+interval '3 minutes'
    WHERE lv_integration_events.lease_until IS NULL OR lv_integration_events.lease_until<now() RETURNING id INTO v_id;
 ELSIF p_action IN ('renew','release') THEN
  UPDATE lv_integration_events SET lease_until=CASE WHEN p_action='renew' THEN now()+interval '3 minutes' END,
   claim_token=CASE WHEN p_action='renew' THEN p_token END
   WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001' AND kind='lock'
    AND (event_key IN ('__worker__','__maintenance__') OR starts_with(event_key,'__conversation__:'))
    AND claim_token=p_token AND (p_action='release' OR lease_until>now()) RETURNING id INTO v_id;
 ELSE RAISE EXCEPTION 'INVALID_ACTION'; END IF;
 RETURN v_id IS NOT NULL;
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_maintenance_lock(p_token uuid)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id uuid;
BEGIN
 IF p_token IS NULL THEN RAISE EXCEPTION 'TOKEN_REQUIRED'; END IF;
 INSERT INTO lv_integration_events(tenant_id,project_id,event_key,kind,status,claim_token,lease_until)
  VALUES('a1b2c3d4-0001-4000-8000-000000000001','b1b2c3d4-0001-4000-8000-000000000001','__maintenance__','lock','completed',p_token,now()+interval '3 minutes')
  ON CONFLICT(project_id,event_key) DO UPDATE SET claim_token=p_token,lease_until=now()+interval '3 minutes'
   WHERE lv_integration_events.lease_until IS NULL OR lv_integration_events.lease_until<now() RETURNING id INTO v_id;
 RETURN v_id IS NOT NULL;
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_contact_lock(p_token uuid,p_contact text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id uuid; held text;
BEGIN
 IF p_token IS NULL OR coalesce(p_contact,'')!~'^([1-9][0-9]*|contact):[1-9][0-9]*$' OR length(p_contact)>200 THEN RAISE EXCEPTION 'INVALID_CONTACT_LEASE'; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('lavilet-conversation-workers'));
 IF EXISTS(SELECT 1 FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001'
   AND event_key='__worker__' AND lease_until>now()) THEN RETURN false; END IF;
 FOR held IN SELECT substr(event_key,length('__conversation__:')+1) FROM lv_integration_events
   WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001' AND kind='lock'
    AND starts_with(event_key,'__conversation__:') AND lease_until>now() LOOP
  IF public.lv_app_resources_overlap(held,p_contact) THEN RETURN false; END IF;
 END LOOP;
 IF (SELECT count(*) FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001'
   AND kind='lock' AND starts_with(event_key,'__conversation__:') AND lease_until>now())>=3 THEN RETURN false; END IF;
 INSERT INTO lv_integration_events(tenant_id,project_id,event_key,kind,status,claim_token,lease_until)
  VALUES('a1b2c3d4-0001-4000-8000-000000000001','b1b2c3d4-0001-4000-8000-000000000001','__conversation__:'||p_contact,'lock','completed',p_token,now()+interval '3 minutes')
  ON CONFLICT(project_id,event_key) DO UPDATE SET claim_token=p_token,lease_until=now()+interval '3 minutes'
   WHERE lv_integration_events.lease_until IS NULL OR lv_integration_events.lease_until<now() RETURNING id INTO v_id;
 RETURN v_id IS NOT NULL;
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_claim_maintenance(p_token uuid)
RETURNS SETOF public.lv_integration_events LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE chosen uuid;
BEGIN
 PERFORM 1 FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001'
  AND event_key='__maintenance__' AND claim_token=p_token AND lease_until>now() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'MAINTENANCE_LEASE_LOST'; END IF;
 UPDATE lv_integration_events e SET status='uncertain',result=jsonb_build_object('reason','WORKER_INTERRUPTED','requires_review',true)
  WHERE e.project_id='b1b2c3d4-0001-4000-8000-000000000001' AND e.status='processing'
   AND (e.kind='decay' OR e.kind='maintenance' AND coalesce(e.payload->>'task','')='')
   AND NOT EXISTS(SELECT 1 FROM lv_integration_events l WHERE l.kind='lock' AND l.claim_token=e.claim_token AND l.lease_until>now());
 SELECT id INTO chosen FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001'
  AND status='pending' AND available_at<=now() AND (kind='decay' OR kind='maintenance' AND coalesce(payload->>'task','')='')
  ORDER BY available_at,ingest_order LIMIT 1 FOR UPDATE SKIP LOCKED;
 RETURN QUERY UPDATE lv_integration_events SET status='processing',claimed_at=now(),claim_token=p_token WHERE id=chosen RETURNING *;
END $$;

-- Account-wide admission, including reads/monitor requests from other instances.
CREATE OR REPLACE FUNCTION public.lv_app_reserve_kommo_call()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE reserved timestamptz; reservation_now timestamptz:=clock_timestamp();
BEGIN
 INSERT INTO lv_integration_events(tenant_id,project_id,event_key,kind,status,lease_until)
 VALUES('a1b2c3d4-0001-4000-8000-000000000001','b1b2c3d4-0001-4000-8000-000000000001','__kommo_rate__','lock','completed',reservation_now+interval '400 milliseconds')
 ON CONFLICT(project_id,event_key) DO UPDATE SET lease_until=greatest(reservation_now,lv_integration_events.lease_until)+interval '400 milliseconds'
 RETURNING lease_until-interval '400 milliseconds' INTO reserved;
 RETURN greatest(0,ceil(extract(epoch FROM reserved-reservation_now)*1000)::integer);
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_reconcile_delivery(p_event uuid,p_actor uuid,p_outcome text,p_reviewed boolean,p_provider_message_id text,p_review_reference text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE e lv_integration_events; evidence kommo_message_evidence; at_time timestamptz:=clock_timestamp();
BEGIN
 IF p_reviewed IS DISTINCT FROM true OR coalesce(p_outcome,'') NOT IN ('sent','not_sent') OR p_actor IS NULL
  OR length(trim(coalesce(p_review_reference,''))) NOT BETWEEN 3 AND 300 THEN RAISE EXCEPTION 'DELIVERY_REVIEW_REQUIRED'; END IF;
 IF NOT EXISTS(SELECT 1 FROM profiles WHERE id=p_actor AND role='admin' AND is_active=true) THEN RAISE EXCEPTION 'DELIVERY_REVIEW_FORBIDDEN'; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('lavilet-conversation-workers'));
 SELECT * INTO e FROM lv_integration_events WHERE id=p_event AND tenant_id='a1b2c3d4-0001-4000-8000-000000000001'
  AND project_id='b1b2c3d4-0001-4000-8000-000000000001' AND kind IN ('inbound','advisor_outbound') FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'INCIDENT_NOT_REVIEWABLE'; END IF;
 IF e.result->>'reconciliation_outcome'=p_outcome AND e.status IN ('completed','cancelled') THEN RETURN jsonb_build_object('reconciled',true,'already_reviewed',true,'contact_key',e.contact_key); END IF;
 IF e.status<>'uncertain' THEN RAISE EXCEPTION 'INCIDENT_NOT_REVIEWABLE'; END IF;
 IF EXISTS(SELECT 1 FROM lv_integration_events l WHERE l.project_id=e.project_id AND l.status='processing' AND public.lv_app_resources_overlap(l.contact_key,e.contact_key))
  OR EXISTS(SELECT 1 FROM lv_integration_events l WHERE l.project_id=e.project_id AND l.kind='lock' AND l.lease_until>now()
   AND (l.event_key='__worker__' OR starts_with(l.event_key,'__conversation__:')
    AND public.lv_app_resources_overlap(substr(l.event_key,length('__conversation__:')+1),e.contact_key))) THEN RAISE EXCEPTION 'WORKER_BUSY'; END IF;
 IF p_outcome='sent' THEN
  SELECT * INTO evidence FROM kommo_message_evidence k WHERE k.tenant_id=e.tenant_id AND k.project_id=e.project_id
   AND k.contact_id=e.payload->>'contactId' AND k.external_message_id=p_provider_message_id AND k.direction='outgoing'
   AND k.delivery_status IN ('sent','delivered','read') AND (k.kommo_lead_id IS NULL OR k.kommo_lead_id=(e.payload->>'kommoId')::bigint)
   AND k.sent_at>=coalesce(e.claimed_at,e.received_at)-interval '1 minute' ORDER BY k.observed_at DESC LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'DELIVERY_EVIDENCE_REQUIRED'; END IF;
 ELSIF nullif(trim(coalesce(p_provider_message_id,'')),'') IS NOT NULL THEN RAISE EXCEPTION 'DELIVERY_OUTCOME_CONFLICT'; END IF;
 UPDATE lv_integration_events SET status=CASE WHEN p_outcome='sent' THEN 'completed' ELSE 'cancelled' END,completed_at=at_time,
  result=coalesce(e.result,'{}'::jsonb)||jsonb_build_object('requires_review',false,'delivery_uncertain',false,
   'reconciliation_outcome',p_outcome,'reviewed_by',p_actor,'reviewed_at',at_time,'review_reference',trim(p_review_reference),
   'provider_message_id',evidence.external_message_id,'delivery_status',CASE WHEN p_outcome='sent' THEN 'confirmed' ELSE 'not_sent' END,'recovery','not_replayed')
 WHERE id=e.id;
 RETURN jsonb_build_object('reconciled',true,'already_reviewed',false,'contact_key',e.contact_key);
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_contact_wakeup(p_contact text)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT jsonb_build_object('event_id',e.id,'due_at',CASE WHEN e.kind='advisor_outbound' THEN e.available_at ELSE
  (SELECT max(p.available_at) FROM lv_integration_events p WHERE p.project_id=e.project_id AND p.contact_key=e.contact_key AND p.status='pending' AND p.kind='inbound') END)
 FROM lv_integration_events e WHERE e.project_id='b1b2c3d4-0001-4000-8000-000000000001' AND e.contact_key=p_contact
  AND e.kind IN ('inbound','advisor_outbound') AND e.status='pending'
  AND (e.kind='advisor_outbound' OR NOT EXISTS(SELECT 1 FROM lv_integration_events u WHERE u.project_id=e.project_id AND public.lv_app_resources_overlap(u.contact_key,e.contact_key) AND u.status='uncertain'))
 ORDER BY CASE e.kind WHEN 'advisor_outbound' THEN 0 ELSE 1 END,e.received_at DESC,e.ingest_order DESC LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.lv_app_claim_contact(p_token uuid,p_contact text)
RETURNS SETOF public.lv_integration_events LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE chosen lv_integration_events; batch_limit integer:=10;
BEGIN
 PERFORM 1 FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001'
  AND event_key='__conversation__:'||p_contact AND kind='lock' AND claim_token=p_token AND lease_until>now() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'CONTACT_LEASE_LOST'; END IF;
 UPDATE lv_integration_events SET status='uncertain',result=jsonb_build_object('reason','WORKER_INTERRUPTED','requires_review',true)
  WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001' AND public.lv_app_resources_overlap(contact_key,p_contact) AND status='processing' AND claim_token IS DISTINCT FROM p_token;
 IF EXISTS(SELECT 1 FROM lv_integration_events WHERE project_id='b1b2c3d4-0001-4000-8000-000000000001' AND public.lv_app_resources_overlap(contact_key,p_contact) AND status='processing') THEN RETURN; END IF;
 SELECT e.* INTO chosen FROM lv_integration_events e WHERE e.project_id='b1b2c3d4-0001-4000-8000-000000000001' AND e.contact_key=p_contact
  AND e.status='pending' AND e.available_at<=now() AND e.kind IN ('inbound','advisor_outbound')
  AND (e.kind='advisor_outbound' OR (NOT EXISTS(SELECT 1 FROM lv_integration_events u WHERE u.project_id=e.project_id AND public.lv_app_resources_overlap(u.contact_key,e.contact_key) AND u.status='uncertain')
   AND NOT EXISTS(SELECT 1 FROM lv_integration_events later WHERE later.project_id=e.project_id AND later.contact_key=e.contact_key AND later.status='pending'
    AND later.kind IN ('inbound','advisor_outbound') AND later.available_at>now())))
  ORDER BY CASE e.kind WHEN 'advisor_outbound' THEN 0 ELSE 1 END,e.received_at,e.ingest_order LIMIT 1 FOR UPDATE SKIP LOCKED;
 IF NOT FOUND THEN RETURN; END IF;
 IF EXISTS(SELECT 1 FROM lv_integration_events WHERE project_id=chosen.project_id AND contact_key=p_contact AND status='pending'
   AND kind='inbound' AND jsonb_typeof(payload->'media')='object') THEN batch_limit:=2; END IF;
 RETURN QUERY WITH picked AS (
  SELECT e.id FROM lv_integration_events e WHERE e.id=chosen.id OR
   (chosen.kind='inbound' AND e.project_id=chosen.project_id AND e.contact_key=p_contact AND e.kind='inbound' AND e.status='pending' AND e.available_at<=now())
  ORDER BY e.received_at,e.ingest_order LIMIT batch_limit FOR UPDATE SKIP LOCKED
 ), claimed AS (
  UPDATE lv_integration_events e SET status='processing',claimed_at=now(),claim_token=p_token WHERE e.id IN (SELECT id FROM picked) RETURNING e.*
 ) SELECT * FROM claimed ORDER BY received_at,ingest_order;
END $$;

CREATE OR REPLACE FUNCTION public.lv_app_claim(p_token uuid)
RETURNS SETOF public.lv_integration_events LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE chosen lv_integration_events; batch_limit integer:=10;
BEGIN
 IF NOT public.lv_app_worker_lock(p_token,'renew') THEN RAISE EXCEPTION 'WORKER_LEASE_LOST'; END IF;
 UPDATE lv_integration_events e SET status='uncertain',result=jsonb_build_object('reason','WORKER_INTERRUPTED','requires_review',true)
  WHERE e.project_id='b1b2c3d4-0001-4000-8000-000000000001' AND e.status='processing' AND e.claim_token IS DISTINCT FROM p_token
   AND NOT EXISTS(SELECT 1 FROM lv_integration_events l WHERE l.kind='lock' AND l.claim_token=e.claim_token AND l.lease_until>now());
 SELECT e.* INTO chosen FROM lv_integration_events e WHERE e.project_id='b1b2c3d4-0001-4000-8000-000000000001'
  AND e.status='pending' AND e.available_at<=now() AND e.kind<>'lock'
  AND NOT (e.kind='decay' OR e.kind='maintenance' AND coalesce(e.payload->>'task','')='')
  AND (e.kind<>'inbound' OR NOT EXISTS(SELECT 1 FROM lv_integration_events later WHERE later.project_id=e.project_id AND later.contact_key=e.contact_key AND later.status='pending' AND later.available_at>now()))
  AND (e.kind='advisor_outbound' OR e.contact_key IS NULL OR NOT EXISTS(SELECT 1 FROM lv_integration_events unresolved WHERE unresolved.project_id=e.project_id AND public.lv_app_resources_overlap(unresolved.contact_key,e.contact_key) AND unresolved.status='uncertain'))
  ORDER BY CASE e.kind WHEN 'advisor_outbound' THEN 0 WHEN 'inbound' THEN 1 ELSE 2 END,e.available_at,e.ingest_order LIMIT 1 FOR UPDATE SKIP LOCKED;
 IF NOT FOUND THEN RETURN; END IF;
 IF EXISTS(SELECT 1 FROM lv_integration_events e WHERE e.project_id=chosen.project_id AND e.contact_key=chosen.contact_key AND e.status='pending' AND jsonb_typeof(e.payload->'media')='object') THEN batch_limit:=2; END IF;
 RETURN QUERY WITH picked AS (
  SELECT e.id FROM lv_integration_events e WHERE e.id=chosen.id OR
   (chosen.kind='inbound' AND e.project_id=chosen.project_id AND e.contact_key=chosen.contact_key AND e.kind='inbound' AND e.status='pending' AND e.available_at<=now())
  ORDER BY e.received_at,e.ingest_order LIMIT batch_limit FOR UPDATE SKIP LOCKED
 ), claimed AS (
  UPDATE lv_integration_events e SET status='processing',claimed_at=now(),claim_token=p_token WHERE e.id IN (SELECT id FROM picked) RETURNING e.*
 ) SELECT * FROM claimed ORDER BY received_at,ingest_order;
END $$;

REVOKE ALL ON FUNCTION public.lv_app_transport_contract(),public.lv_app_resources_overlap(text,text),public.lv_app_maintenance_lock(uuid),public.lv_app_claim_maintenance(uuid),public.lv_app_reserve_kommo_call(),public.lv_app_reconcile_delivery(uuid,uuid,text,boolean,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.lv_app_transport_contract(),public.lv_app_resources_overlap(text,text),public.lv_app_maintenance_lock(uuid),public.lv_app_claim_maintenance(uuid),public.lv_app_reserve_kommo_call(),public.lv_app_reconcile_delivery(uuid,uuid,text,boolean,text,text) TO service_role;
NOTIFY pgrst,'reload schema';
COMMIT;
